# Generated by Django 3.1.3 on 2020-11-08 11:49

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('permission_type', models.SmallIntegerField(choices=[(0, '管理员'), (1, '普通用户')], default=1, verbose_name='permission_type')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'db_table': 'sso_user',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='id')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('expires_time', models.DateTimeField(blank=True, null=True, verbose_name='expires_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='sso.user', verbose_name='User')),
            ],
            options={
                'db_table': 'sso_token',
            },
        ),
    ]
