# Generated by Django 3.1.3 on 2020-11-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(help_text='文章标题', max_length=64, verbose_name='标题')),
                ('summary', models.CharField(help_text='文章摘要', max_length=255, null=True, verbose_name='摘要')),
                ('read_count', models.IntegerField(default=0, editable=False, verbose_name='浏览量')),
                ('like_count', models.IntegerField(default=0, editable=False, help_text='点赞数', verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, editable=False, help_text='评论数', verbose_name='评论数')),
                ('is_essence', models.BooleanField(default=False, verbose_name='是否精华')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='是否允许评论')),
            ],
            options={
                'db_table': 'myecho_article',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='分类名', max_length=64, verbose_name='分类名')),
                ('father_classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myecho_article.classification', verbose_name='父级分类')),
            ],
            options={
                'db_table': 'myecho_classification',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.TextField(null=True, verbose_name='文章内容')),
                ('article', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='myecho_article.article', verbose_name='文章')),
            ],
            options={
                'db_table': 'myecho_article_detail',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myecho_article.classification', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='sso.user', verbose_name='作者'),
        ),
    ]
